export const FEATURE_SLUGS = {
  // Generated dynamically from MODULE_PERMISSIONS
  // Example: BRANCH = 'branch', BRAND = 'brand'
  // You just need to ensure MODULE_PERMISSIONS contains all unique modules
  // and this file will stay up-to-date
  BRANCH: 'branch',
  BRAND: 'brand',
  CATEGORY: 'category',
  CMS: 'cms',
  CONCERN: 'concern',
  CUSTOMER: 'customer',
  DASHBOARD: 'dashboard',
  FLASH_SALES: 'flash_sales',
  INVENTORY: 'inventory',
  ITEM: 'item',
  ORDERS: 'orders',
  PROMO_CODES: 'promo_codes',
  REFERRAL: 'referral',
  REPORTS: 'reports',
  REVIEW: 'review',
  ROLES: 'roles',
  SPIN_WHEEL: 'spin_wheel',
  SUPPLIER: 'supplier',
  TAGS: 'tags',
  USER: 'user',
  ZONE: 'zone',
  IMAGE_LIBRARY: 'image_library',
  IMPORT_EXPORT: 'import_export',
  ACTIVITY_LOG: 'activity_log',
  POPUP: 'popup',
  COLLECTION: 'collection',
  BUNDLE: 'bundle',

  USERS: 'USERS',
  CONTENTS: 'CONTENTS',
  CATEGORIES: 'CATEGORIES',
  SUBSCRIPTIONS: 'SUBSCRIPTIONS',
  FAQS: 'FAQS',
  STATIC_CONTENT: 'STATIC_CONTENT',
  GENRES: 'GENRES',
  // COLLECTION: 'COLLECTION',
  BUNDEL: 'BUNDEL',
  CONCERNS: 'CONCERNS',
  MOBILE_APP_CMS: 'MOBILE_APP_CMS',
  CUSTOMER_ORDER: 'CUSTOMER_ORDER',
  CUSTOMER_TRANSACTION: 'CUSTOMER_TRANSACTION',
} as const;
